#!/usr/bin/env bash
set -euo pipefail

# bootstrap_first_run.sh
# A small first-run bootstrap that:
# - checks for python3 and a repo venv (apps/backend/.venv)
# - creates the venv and installs requirements if missing
# - checks that required ports (8000, 8001) are free
# - writes a basic .env into ForgeTM/apps/backend/.env if not present
# This script is intended for developer convenience on macOS/Linux.

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BACKEND_DIR="$REPO_ROOT/ForgeTM/apps/backend"
VENV_DIR="$BACKEND_DIR/.venv"
REQUIREMENTS_FILE="$BACKEND_DIR/requirements.txt"
ENV_FILE="$BACKEND_DIR/.env"

echo "Repo root: $REPO_ROOT"

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required but not found. Install Python 3.11+ and re-run." >&2
  exit 1
fi

PYTHON_BIN="$(python3 -c 'import sys; print(sys.executable)')"
echo "Using python: $PYTHON_BIN"

if [[ ! -d "$VENV_DIR" ]]; then
  echo "Creating virtualenv at $VENV_DIR"
  python3 -m venv "$VENV_DIR"
else
  echo "Virtualenv exists at $VENV_DIR"
fi

echo "Activating venv and installing requirements (if present)"
source "$VENV_DIR/bin/activate"
if [[ -f "$REQUIREMENTS_FILE" ]]; then
  pip install --upgrade pip
  pip install -r "$REQUIREMENTS_FILE"
else
  echo "No requirements.txt found at $REQUIREMENTS_FILE — skipping pip install"
fi

check_port(){
  local port=$1
  if lsof -i tcp:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "Port $port is in use" >&2
    return 1
  else
    echo "Port $port is free"
    return 0
  fi
}

PORTS=(8000 8001)
for p in "${PORTS[@]}"; do
  check_port "$p" || echo "If you expect the backend to run on $p, stop the process holding it or change the port."
done

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Writing default .env to $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
# Generated by bootstrap_first_run.sh
APP_ENV=development
DATABASE_URL=sqlite:///data/dev.db
SECRET_KEY=replace-me-with-real-secret
UVICORN_HOST=127.0.0.1
UVICORN_PORT=8000
EOF
  echo "Wrote $ENV_FILE (remember to update secrets and production settings)."
else
  echo ".env already exists at $ENV_FILE — leaving untouched"
fi

echo "Bootstrap complete. To start the backend (dev):"
echo "  source $VENV_DIR/bin/activate && uvicorn forge.main:app --reload --host 127.0.0.1 --port 8000"
